name = "ContinuumWorld"
uuid = "5cbb95a3-277b-5373-895a-7e14bd91b3cc"
repo = "https://github.com/JuliaPOMDP/ContinuumWorld.jl"
version = "0.3.0"

[deps]
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
POMDPs = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"

[targets]
test = ["Test", "POMDPSimulators"]
