name = "ContinuumWorld"
uuid = "5cbb95a3-277b-5373-895a-7e14bd91b3cc"
repo = "https://github.com/JuliaPOMDP/ContinuumWorld.jl"
version = "0.3.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
POMDPs = "0.9,1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
